DEFAULT_BUNDLE_SCOPE = "Default-Bundle-Scope"
REQUEST_OVERLAY_GROUP = "Request-Overlay-Group"
PATH_OF_RX_APP_DATAPAGE = "/api/rx/application/datapage"
PATH_OF_RX_APP_COMMAND = "/api/rx/application/command"
PROCESS_DEFINITION_PATH = "/api/rx/application/process/processdefinition"
RECORD_DEFINITION_PATH = "/api/rx/application/record/recorddefinition"
RX_ATTACHMENT_PATH = "/api/rx/application/record/attachment"
RECORD_INSTANCE_PATH = "/api/rx/application/record/recordinstance"
RECORD_DEFINITION_DATA_PAGE_QUERY = "com.bmc.arsys.rx.application.record.datapage.RecordDefinitionDataPageQuery"
RECORD_INSTANCE_DATA_PAGE_QUERY = "com.bmc.arsys.rx.application.record.datapage.RecordInstanceDataPageQuery"
PROCESS_INSTANCE_PATH = "/api/rx/application/process/processinstance"
PROCESS_INSTANCE_DATA_PAGE_QUERY = "com.bmc.arsys.rx.application.process.datapage.ProcessInstanceDataPageQuery"
PROCESS_INSTANCE_COUNTS_BY_STATUS_DATA_PAGE_QUERY = "com.bmc.arsys.rx.application.process.datapage.ProcessInstanceCountsByStatusDataPageQuery"
ADMIN_COMPONENT_DATA_PAGE_QUERY = "com.bmc.arsys.rx.application.admin.datapage.AdminComponentDataPageQuery"
ADMIN_COMPONENT_PATH = "/api/rx/application/admin-settings/component"
ASSOCIATION_DEFINITION_PATH = "/api/rx/application/association/associationdefinition"
ASSOCIATION_DEFINITION_DATA_PAGE_QUERY = "com.bmc.arsys.rx.application.association.datapage.AssociationDefinitionDataPageQuery"
DOCUMENT_DEFINITION_DATA_PAGE_QUERY = "com.bmc.arsys.rx.application.document.datapage.DocumentDefinitionDataPageQuery"
DOCUMENT_DEFINITION_PATH = "/api/rx/application/document/documentdefinition"
NAMEDLIST_DEFINITION_DATA_PAGE_QUERY = "com.bmc.arsys.rx.application.namedlist.datapage.NamedListDefinitionDataPageQuery"
NAMEDLIST_DEFINITION_PATH = "/api/rx/application/namedlist/namedlistdefinition"
RULE_DEFINITION_DATA_PAGE_QUERY = "com.bmc.arsys.rx.application.rule.datapage.RuleDefinitionDataPageQuery"
RULE_DEFINITION_PATH = "/api/rx/application/rule/ruledefinition"
VIEW_DEFINITION_PATH = "/api/rx/application/view/viewdefinition"
VIEW_DEFINITION_DATA_PAGE_QUERY = "com.bmc.arsys.rx.application.view.datapage.ViewDefinitionDataPageQuery"


